name: acid
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - black
    - hypy_utils
    - jsonargparse[signatures]
    - librosa
    - matplotlib==3.7.3
    - numba
    - numpy==1.23.5
    - pandas
    - pytorch-lightning
    - resampy
    - scipy==1.11.2
    - torch
    - torchaudio
    - torchvision
    - tensorboard
    - wandb
    - git+https://github.com/Neutone/neutone_sdk.git@c69108d6ad11910afdc3ce4ead0a647456e2addb
