name: acid
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - lightning
  - numba
  - cudatoolkit=11.8
  - pip:
    - auraloss
    - black
    - hypy_utils
    - jsonargparse[signatures]
    - librosa
    - matplotlib==3.7.3
    - numpy==1.23.5
    - nvitop
    - pandas
    - resampy
    - scipy==1.11.2
    - tensorboard
    - wandb
    - git+https://github.com/Neutone/neutone_sdk.git@c69108d6ad11910afdc3ce4ead0a647456e2addb
