class_path: audio_config.AudioConfig
init_args:
  sr: 48000
  buffer_size_seconds: 0.125
  note_on_duration: -1

  min_attack: 0.001
  max_attack: 0.001
  min_decay: 0.124
  max_decay: 0.124
  min_sustain: 0.0
  max_sustain: 0.0
  min_release: 0.001
  max_release: 0.001
  min_alpha: 1.0
  max_alpha: 1.0

  min_f0_hz: -1
  max_f0_hz: -1
  min_w_hz: 100.0
  max_w_hz: 8000.0
  min_q: 0.7071
  max_q: 8.0
  min_dist_gain: 0.01
  max_dist_gain: 4.0
  min_osc_shape: 0.0
  max_osc_shape: 1.0
  min_osc_gain: 0.01
  max_osc_gain: 1.0
  min_learned_alpha: 0.1
  max_learned_alpha: 6.0

  stability_eps: 0.001
